---

- hosts: loadbalancer
  gather_facts: false
  become: true
  tasks:
    - name: stop nginx
      service: name=nginx state=stopped

    - name: verify nginx port drained
      wait_for: port=80 state=drained

    
- hosts: webserver
  gather_facts: false  
  become: true
  tasks:
    - name: stopping apache2
      service: name=apache2 state=stopped

    - name: verify apache2 port drained
      wait_for: port=80 state=drained


- hosts: database
  name: stopping mysql
  become: true
  tasks:
    - service: name=mysql state=stopped

    - name: verify mysql stopped and port 3306 drained
      wait_for: port=3306 host={{ansible_default_ipv4.address}} timeout=30 state=drained