---
- hosts: database
  name: starting mysql
  become: true
  tasks:
    - service: name=mysql state=started

    - name: verify mysql started and listening on port 3306
      wait_for: port=3306 host={{ansible_default_ipv4.address}} timeout=30

- hosts: webserver
  name: starting apache2
  gather_facts: false
  become: true
  tasks:
    - service: name=apache2 state=started

    - name: apache2 status
      command: systemctl is-active apache2 
      ignore_errors: yes
      register: out
      changed_when: false

    - name: verify apache2 started and listening on port 80
      wait_for: port=80 timeout=30
    
    - debug: var=out.stdout_lines

- hosts: loadbalancer
  name: starting nginx
  gather_facts: false
  become: true
  
  tasks:
    - service: name=nginx state=started

    - name: nginx status
      command: systemctl is-active nginx 
      ignore_errors: yes
      register: out
      changed_when: false
      

    - name: verify nginx started and listening on port 80
      wait_for: port=80 timeout=30
    
    - debug: var=out.stdout_lines