---
  - name: install dependencies
    apt: 
      name: ['python-mysqldb']
      state: present

  - name: install mysql-server
    apt: name=mysql-server state=present update_cache=yes

  - name: ensure listening on all ports
    lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp="bind-address" line="bind-address = {{ansible_default_ipv4.address}}"
    notify: restart db

  - name: mysql check
    service: name=mysql state=started enabled=true

  - name: create db
    mysql_db: name={{db_name}} state=present

  - debug:
      msg: " name={{db_name}}"

  - name: create user
    mysql_user: name={{db_username}} password={{db_user_pass}} priv={{db_name}}.*:ALL host='{{db_user_host}}' state=present
    notify: restart db
